
CREATE TABLE IF NOT EXISTS eleitor (
    IDELEITOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL,
    TITULO VARCHAR(12) NOT NULL UNIQUE,
    ZONA VARCHAR(4) NOT NULL,
    SECAO VARCHAR(4) NOT NULL 
);

CREATE TABLE IF NOT EXISTS cargo (
    IDCARGO INT PRIMARY KEY AUTO_INCREMENT,
    NUMDIGITOS INT NOT NULL,
    NOMECARGO VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS partido (
    NUMPARTIDO INT PRIMARY KEY, 
    NOMEPARTIDO VARCHAR(100) NOT NULL,
    SIGLA VARCHAR(10) NOT NULL
);


CREATE TABLE IF NOT EXISTS candidato (
    IDCANDIDATO INT PRIMARY KEY AUTO_INCREMENT,
    NOMECANDIDATO VARCHAR(150) NOT NULL,
    NUMPARTIDO INT NOT NULL,
    IDCARGO INT NOT NULL,
    CONSTRAINT fk_partido FOREIGN KEY (NUMPARTIDO) REFERENCES partido(NUMPARTIDO),
    CONSTRAINT fk_cargo FOREIGN KEY (IDCARGO) REFERENCES cargo(IDCARGO)
);