name: CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
      - run: pip install -r requirements.txt

      - name: Generate Tag
        id: generate_tag
        run: | 
              SHA=$(echo $GITHUB_SHA | head -c7)
              echo "sha=$SHA" >> $GITHUB_OUTPUT 
      
      - name: Build Docker image
        run: docker build -t election_app:${{ steps.generate_tag.outputs.sha }} .

      
